CREATE TABLE TB_USER
(
    ID         UUID PRIMARY KEY NOT NULL,
    NAME       VARCHAR          NOT NULL,
    EMAIL      VARCHAR          NOT NULL UNIQUE,
    PASSWORD   VARCHAR(64)      NOT NULL,
    IS_ACTIVE  BOOLEAN          NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE TB_USER IS 'User table';
COMMENT ON COLUMN TB_USER.NAME IS 'User name';
COMMENT ON COLUMN TB_USER.ID IS 'Users primary key';
COMMENT ON COLUMN TB_USER.EMAIL IS 'User email to login';
COMMENT ON COLUMN TB_USER.PASSWORD IS 'User password hash';
COMMENT ON COLUMN TB_USER.IS_ACTIVE IS 'User active status flag for spring security';