CREATE TABLE "INSTRUMENT" (
    ID         UUID PRIMARY KEY NOT NULL,
    NAME       VARCHAR          NOT NULL,
    CREATED_AT TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "INSTRUMENT" IS 'Instrument table';
COMMENT ON COLUMN "INSTRUMENT".NAME IS 'Instrument name';
COMMENT ON COLUMN "INSTRUMENT".ID IS 'Instruments primary key';