CREATE TABLE "USER_INSTRUMENT"
(
    USER_ID       UUID             NOT NULL REFERENCES TB_USER (ID),
    INSTRUMENT_ID UUID           NOT NULL REFERENCES "INSTRUMENT" (ID),
    CREATED_AT    TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, INSTRUMENT_ID)
);

COMMENT ON TABLE "USER_INSTRUMENT" IS 'User instrument table';
COMMENT ON COLUMN "USER_INSTRUMENT".USER_ID IS 'User id';
COMMENT ON COLUMN "USER_INSTRUMENT".INSTRUMENT_ID IS 'Instrument id';