CREATE TABLE "WORSHIP_MINISTRY"
(
    ID         UUID PRIMARY KEY NOT NULL,
    NAME       VARCHAR          NOT NULL,
    CREATED_AT TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "WORSHIP_MINISTRY" IS 'Worship ministry table';
COMMENT ON COLUMN "WORSHIP_MINISTRY".NAME IS 'Worship ministry name';
COMMENT ON COLUMN "WORSHIP_MINISTRY".ID IS 'Worship ministry primary key';