CREATE TABLE "REPERTORY"
(
    ID         UUID PRIMARY KEY NOT NULL,
    PLAY_DATE  DATE             NOT NULL,
    CREATED_AT TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "REPERTORY" IS 'Repertory table';
COMMENT ON COLUMN "REPERTORY".ID IS 'Repertory primary key';
COMMENT ON COLUMN "REPERTORY".PLAY_DATE IS 'Date of the repertory play';