CREATE TABLE "USER_MINISTRY"
(
    USER_ID     UUID      NOT NULL,
    MINISTRY_ID UUID      NOT NULL,
    IS_ADMIN    BOOLEAN   NOT NULL DEFAULT FALSE,
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, MINISTRY_ID),
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID),
    FOREIGN KEY (MINISTRY_ID) REFERENCES "WORSHIP_MINISTRY" (ID)
);

COMMENT ON TABLE "USER_MINISTRY" IS 'User ministry table';
COMMENT ON COLUMN "USER_MINISTRY".USER_ID IS 'User id';
COMMENT ON COLUMN "USER_MINISTRY".MINISTRY_ID IS 'Ministry id';
COMMENT ON COLUMN "USER_MINISTRY".IS_ADMIN IS 'User admin status flag for ministry';