CREATE TABLE "REPERTORY_MUSIC"
(
    REPERTORY_ID UUID NOT NULL REFERENCES "REPERTORY" (ID),
    MUSIC_ID     UUID NOT NULL REFERENCES "MUSIC" (ID),
    OBSERVATION  VARCHAR(255),
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (REPERTORY_ID, MUSIC_ID)
);