CREATE TABLE "REPERTORY_MUSIC"
(
    REPERTORY_ID UUID NOT NULL,
    MUSIC_ID     UUID NOT NULL,
    OBSERVATION  VARCHAR(255),
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (REPERTORY_ID, MUSIC_ID),
    FOREIGN KEY (REPERTORY_ID) REFERENCES "REPERTORY" (ID),
    FOREIGN KEY (MUSIC_ID) REFERENCES "MUSIC" (ID)
);